wandb_version: 1

train_window:
  desc: null
  value: 128
pred_window:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 8.0e-05
input_size:
  desc: null
  value: 5
hidden_size:
  desc: null
  value: 1024
output_size:
  desc: null
  value: 32
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712260456.030909
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
