wandb_version: 1

train_window:
  desc: null
  value: 256
pred_window:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 5.0e-05
input_size:
  desc: null
  value: 8
hidden_size:
  desc: null
  value: 1256
output_size:
  desc: null
  value: 8
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 12
coins:
  desc: null
  value:
  - BTC
  - ETH
  - XRP
  - BNB
  - DOGE
  - ADA
  - SOL
  - DOT
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712858656.307823
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 3
      - 5
      - 13
      13: windows-amd64
